In [2]:
import tensorflow as tf

hello = tf.constant('Hello, Tensorflow')
print(hello)

a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print(c)



Tensor("Const:0", shape=(), dtype=string)
Tensor("Add:0", shape=(), dtype=int32)


In [3]:
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a,b,c]))

sess.close();

b'Hello, Tensorflow'
[10, 32, 42]


In [6]:
X = tf.placeholder(tf.float32, [None, 3])
print(X)

x_data = [[1,2,3], [4,5,6]]

W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

expr = tf.matmul(X, W) + b

Tensor("Placeholder_2:0", shape=(?, 3), dtype=float32)


In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print('=== x_data ===')
print(x_data)
print('=== W ===')
print(sess.run(W))
print('=== b ===')
print(sess.run(b))
print('=== expr ===')
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 0.12846157 -0.26115435]
 [-0.28825551  0.97823101]
 [ 0.57969713  0.46662167]]
=== b ===
[[ 1.54604721]
 [-1.28808057]]
=== expr ===
[[ 2.83708906  4.64122009]
 [ 1.26267111  5.3581872 ]]


In [16]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

X = tf.placeholder(tf.float32, name='X')
Y = tf.placeholder(tf.float32, name='Y')

hypothesis = W * X + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

In [20]:
x_data = [1,2,3]
y_data = [1,2,3]

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, sess.run(W), sess.run(b))
    
    print("\n=== Test ===")
    print("X: 5, Y: {}".format(sess.run(hypothesis, feed_dict={X: 5})))
    print("X: 2.5, Y: {}".format(sess.run(hypothesis, feed_dict={X: 2.5})))
    
    

0 21.1818 [ 1.00457287] [ 0.51967889]
1 0.279669 [ 0.79243332] [ 0.41391397]
2 0.0287241 [ 0.82059664] [ 0.41415784]
3 0.0245208 [ 0.82237667] [ 0.40308762]
4 0.0233221 [ 0.82692337] [ 0.3935194]
5 0.0222139 [ 0.83105379] [ 0.38404617]
6 0.0211587 [ 0.83511847] [ 0.3748154]
7 0.0201537 [ 0.83908176] [ 0.36580494]
8 0.0191963 [ 0.84295017] [ 0.35701126]
9 0.0182845 [ 0.84672546] [ 0.34842893]
10 0.017416 [ 0.8504101] [ 0.34005296]
11 0.0165887 [ 0.85400611] [ 0.33187833]
12 0.0158007 [ 0.85751569] [ 0.32390022]
13 0.0150502 [ 0.86094099] [ 0.31611392]
14 0.0143353 [ 0.8642838] [ 0.30851474]
15 0.0136544 [ 0.86754632] [ 0.30109826]
16 0.0130058 [ 0.8707304] [ 0.29386008]
17 0.012388 [ 0.87383801] [ 0.28679591]
18 0.0117995 [ 0.87687081] [ 0.27990153]
19 0.0112391 [ 0.87983078] [ 0.27317291]
20 0.0107052 [ 0.88271958] [ 0.26660603]
21 0.0101967 [ 0.88553888] [ 0.26019698]
22 0.00971234 [ 0.88829046] [ 0.25394204]
23 0.009251 [ 0.89097583] [ 0.24783744]
24 0.00881157 [ 0.89359671] [ 0.2418